# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: LLM4Code 2024
description: >- # this means to ignore newlines until "baseurl:"
  ICSE 2024 Workshop on Large Language Model for Code
baseurl: "" # the subpath of your site, e.g. /blog
domain: llm4code.github.io
url: "https://llm4code.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username: llm4code
x_username: llm4code

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

header_pages:
  - index.md
  - program.md
  - speakers.md
  - call.md
  - dates.md
  - organization.md
  - pc.md

twitter:
  username: llm4code
  card: summary

defaults:
  - scope:
      path: ""
    values:
      image: /assets/llm4code-logo-light.png

exclude: ["README.md", "Gemfile", "Gemfile.lock", "LICENSE"]
# This setting does not work and would be overrided
# https://github.com/github/pages-gem/blob/e70dc2860262bc43be02172dde070d1884785084/lib/github-pages/configuration.rb#L57
# kramdown:
# math_engine: katex
